import Configs from "./(routes)/Configs";

import "@/assets/css/global/global.scss";
import "@/assets/css/colors/colors.scss";
// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import Header from "@/components/layout/Header/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      {/* <Script
        src='https://www.paypal.com/sdk/js?client-id=BAAxZ8X6Jrip-0ZbGzxyX2RQAC5PWapiFLZdprn8jIAXMFUUjFKI8YnuJqhbE0tolJ-FMavoXfDaUB6wUA&components=hosted-buttons&disable-funding=venmo&currency=USD'
        crossOrigin='anonymous'
        async></Script> */}

      <body className='App'>
        <Configs>
          <Header />
          <>{children}</>
        </Configs>
      </body>
    </html>
  );
}
