import Configs from "./(routes)/Configs";

import "@/assets/css/global/global.scss";
import "@/assets/css/colors/colors.scss";
import Header from "@/components/layout/Header/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='App'>
        <Header/>
        <Configs>
          <>{children}</>
        </Configs>
      </body>
    </html>
  );
}
